

import java.awt.Color;
import java.io.PrintStream;
import java.util.*;
import javax.swing.*;
import java.text.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jimmy
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSource = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("AreaCirculo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Calificacion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Dado");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("DadosModificados2");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("GraficaCalificaciones2");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("NumeroMayor");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("SimulacionDado2");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("SimulacionJuego");

        jButton9.setText("SumaArreglos2");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Tabla");

        jLabel1.setText("Código Fuente");

        jLabel2.setText("Salida");

        txtSource.setColumns(20);
        txtSource.setRows(5);
        jScrollPane1.setViewportView(txtSource);

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        jScrollPane2.setViewportView(txtOutput);

        jLabel3.setText("Programas:");

        jMenu1.setText("File");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Close");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton6)
                                    .addComponent(jButton7)
                                    .addComponent(jButton10)
                                    .addComponent(jButton9)
                                    .addComponent(jButton8))
                                .addGap(24, 24, 24)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(80, 80, 80))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        aCirculo();
        saCirculo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        pDado();
        sPDado();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        desactivarCampo();
        colorBox();
    }//GEN-LAST:event_formWindowOpened

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Calif();
        sCalif();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DModificados();
        sDModificados();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        gCalif();
        sgCalif();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        sNMayor();
        NMayor();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Dado2();
        sDado2();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        SumaArreglos2();
        rSumaArreglos2();
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea txtOutput;
    private javax.swing.JTextArea txtSource;
    // End of variables declaration//GEN-END:variables

    private void desactivarCampo(){
        this.txtSource.setEditable(false);
        this.txtOutput.setEditable(false);
    }

    private void colorBox() {
        this.txtSource.setBackground(Color.YELLOW);
    }
    
    private void pDado()
    {
        int suma1 = 0, suma2 = 0;
        for (int i = 1; i <= 5; i++)
        {
            int x = (int)(Math.random()*6+1);
            this.txtOutput.append("Turno "+i+"/5!\nJugador 1 avento el dado!\nCayo en: "+x+"!\n");
            suma1+=x;
            int y = (int)(Math.random()*6+1);
            this.txtOutput.append("Jugador 2 avento el dado!\nCayo en: "+y+"!\n");
            suma2+=y;
            txtOutput.append("------------------------------\n");
        }
        if (suma1 > suma2)
        {
            this.txtOutput.append("Resultados:\nJugador 1: "+suma1+"\nJugador 2: "+suma2+"\nJugador 1 gana!\n");
        }
        if (suma1 < suma2)
        {
            this.txtOutput.append("Resultados:\nJugador 1: "+suma1+"\nJugador 2: "+suma2+"\nJugador 2 gana!\n");
        }
        if (suma1 == suma2)
        {
            this.txtOutput.append("Resultados:\nJugador 1: "+suma1+"\nJugador 2: "+suma2+"\nEmpate!\n");
        }
        txtOutput.append("------------------------------\n");
    }
    public void Test()
    {
        txtOutput.append("Woop!\n");
        txtOutput.append("LOL");
    }
    private void sPDado()
    {
        this.txtSource.setText("int suma1 = 0, suma2 = 0;\n" +
"        for (int i = 1; i <= 5; i++)\n" +
"        {\n" +
"            int x = (int)(Math.random()*6+1);\n" +
"            this.txtOutput.append(\"Turno \"+i+\"/5!\\nJugador 1 avento el dado!\\nCayo en: \"+x+\"!\\n\");\n" +
"            suma1+=x;\n" +
"            int y = (int)(Math.random()*6+1);\n" +
"            this.txtOutput.append(\"Jugador 2 avento el dado!\\nCayo en: \"+y+\"!\\n\");\n" +
"            suma2+=y;\n" +
"            txtOutput.append(\"------------------------------\\n\");\n" +
"        }\n" +
"        if (suma1 > suma2)\n" +
"        {\n" +
"            this.txtOutput.append(\"Resultados:\\nJugador 1: \"+suma1+\"\\nJugador 2: \"+suma2+\"\\nJugador 1 gana!\\n\");\n" +
"        }\n" +
"        if (suma1 < suma2)\n" +
"        {\n" +
"            this.txtOutput.append(\"Resultados:\\nJugador 1: \"+suma1+\"\\nJugador 2: \"+suma2+\"\\nJugador 2 gana!\\n\");\n" +
"        }\n" +
"        if (suma1 == suma2)\n" +
"        {\n" +
"            this.txtOutput.append(\"Resultados:\\nJugador 1: \"+suma1+\"\\nJugador 2: \"+suma2+\"\\nEmpate!\\n\");\n" +
"        }\n" +
"    }\n" +
"           txtOutput.append(\"------------------------------\\n\");");
    }
    private void aCirculo()
    {
        double radio, area;
        DecimalFormat df = new DecimalFormat("#.###");
        radio = (double)(Math.random()*100)+1;
        this.txtOutput.append("El radio de la circunferencia es de: "+df.format(radio)+"\n");
        area = Math.PI*Math.pow(radio,2);
        this.txtOutput.append("El area de la circunferencia es: \n"+df.format(area)+"\n");
        this.txtOutput.append("------------------------------\n");
    }
    private void saCirculo()
    {
        txtSource.setText("double radio, area;\n" +
"        DecimalFormat df = new DecimalFormat(\"#.###\");\n" +
"        radio = (double)(Math.random()*100)+1;\n" +
"        this.txtOutput.append(\"El radio de la circunferencia es de: \"+df.format(radio)+\"\\n\");\n" +
"        area = Math.PI*Math.pow(radio,2);\n" +
"        this.txtOutput.append(\"El area de la circunferencia es: \\n\"+df.format(area)+\"\\n\");\n" +
"        this.txtOutput.append(\"------------------------------\\n\");");
    }
    private void Calif()
    {
        int cal;
        cal = (int)(Math.random()*100);
        txtOutput.append("La calificacion es de: "+cal+"\n");
        if (cal >= 70)
        {
            txtOutput.append("Calificacion aprobada.\n");
        }
        else
        {
            txtOutput.append("Calificacion reprobada.\n");
        }
        txtOutput.append("------------------------------\n");
    }
    private void sCalif()
    {
        txtSource.setText("        int cal;\n" +
"        cal = (int)(Math.random()*100);\n" +
"        txtOutput.append(\"La calificacion es de: \"+cal+\"\\n\");\n" +
"        if (cal >= 70)\n" +
"        {\n" +
"            txtOutput.append(\"Calificacion aprobada.\\n\");\n" +
"        }\n" +
"        else\n" +
"        {\n" +
"            txtOutput.append(\"Calificacion reprobada.\\n\");\n" +
"        }\n" +
"        txtOutput.append(\"------------------------------\\n\");");
    }
    private void DModificados() {
        int x[] = new int [7];
        for(int i = 1; i <= 10000; i++)
        {
            int rand = (int)(Math.random()*7+0);
            x[rand]++;
        }
        int a = x[2]+x[6];
        txtOutput.append("Frecuencia del dado en 10000 intentos:\nCara 1: "+x[0]+"\nCara 2: "+x[1]+"\nCara 3: "+a+"\nCara 4: "+x[3]+"\nCara 5: "+x[4]+"\nCara 6: "+x[5]+"\n");
        txtOutput.append("------------------------------\n");
    }
    private void sDModificados(){
        txtSource.setText("int x[] = new int [7];\n" +
"        for(int i = 1; i <= 10000; i++)\n" +
"        {\n" +
"            int rand = (int)(Math.random()*7+0);\n" +
"            x[rand]++;\n" +
"        }\n" +
"        int a = x[2]+x[6];\n" +
"        txtOutput.append(\"Frecuencia del dado en 10000 intentos:\\nCara 1: \"+x[0]+\"\\nCara 2: \"+x[1]+\"\\nCara 3: \"+a+\"\\nCara 4: \"+x[3]+\"\\nCara 5: \"+x[4]+\"\\nCara 6: \"+x[5]+\"\\n\");\n" +
"        txtOutput.append(\"------------------------------\\n\");");
    }
    private void gCalif(){
        int x[] = new int [6];
        for(int i = 1; i <= 30; i++)
        {
            int rand = (int)(Math.random()*6+0);
            x[rand]++;
        }
        txtOutput.append("Frecuencia de calificaciones:\n");
        
        txtOutput.append("5 =  ");
        for (int j = 1; x[0] > 0; j++)
        {
            x[0]--;
            txtOutput.append("*");
        }
        
        int j = 1;
        
        txtOutput.append("\n6 =  ");
        for (j = 1; x[1] > 0; j++)
        {
            x[1]--;
            txtOutput.append("*");
        }
        
        j = 1;
        
        txtOutput.append("\n7 =  ");
        for (j = 1; x[2] > 0; j++)
        {
            x[2]--;
            txtOutput.append("*");
        }
        
        j = 1;
        
        txtOutput.append("\n8 =  ");
        for (j = 1; x[3] > 0; j++)
        {
            x[3]--;
            txtOutput.append("*");
        }
        
        j = 1;
        
        txtOutput.append("\n9 =  ");
        for (j = 1; x[4] > 0; j++)
        {
            x[4]--;
            txtOutput.append("*");
        }
        
        j = 1;
        
        txtOutput.append("\n10 = ");
        for (j = 1; x[5] > 0; j++)
        {
            x[5]--;
            txtOutput.append("*");
        }
        
        txtOutput.append("\n------------------------------\n");
    }
    private void sgCalif()
    {
        txtSource.setText("private void gCalif(){\n" +
"        int x[] = new int [6];\n" +
"        for(int i = 1; i <= 30; i++)\n" +
"        {\n" +
"            int rand = (int)(Math.random()*6+0);\n" +
"            x[rand]++;\n" +
"        }\n" +
"        txtOutput.append(\"Frecuencia de calificaciones:\\n\");\n" +
"        \n" +
"        txtOutput.append(\"5 =  \");\n" +
"        for (int j = 1; x[0] > 0; j++)\n" +
"        {\n" +
"            x[0]--;\n" +
"            txtOutput.append(\"*\");\n" +
"        }\n" +
"        \n" +
"        int j = 1;\n" +
"        \n" +
"        txtOutput.append(\"\\n6 =  \");\n" +
"        for (j = 1; x[1] > 0; j++)\n" +
"        {\n" +
"            x[1]--;\n" +
"            txtOutput.append(\"*\");\n" +
"        }\n" +
"        \n" +
"        j = 1;\n" +
"        \n" +
"        txtOutput.append(\"\\n7 =  \");\n" +
"        for (j = 1; x[2] > 0; j++)\n" +
"        {\n" +
"            x[2]--;\n" +
"            txtOutput.append(\"*\");\n" +
"        }\n" +
"        \n" +
"        j = 1;\n" +
"        \n" +
"        txtOutput.append(\"\\n8 =  \");\n" +
"        for (j = 1; x[3] > 0; j++)\n" +
"        {\n" +
"            x[3]--;\n" +
"            txtOutput.append(\"*\");\n" +
"        }\n" +
"        \n" +
"        j = 1;\n" +
"        \n" +
"        txtOutput.append(\"\\n9 =  \");\n" +
"        for (j = 1; x[4] > 0; j++)\n" +
"        {\n" +
"            x[4]--;\n" +
"            txtOutput.append(\"*\");\n" +
"        }\n" +
"        \n" +
"        j = 1;\n" +
"        \n" +
"        txtOutput.append(\"\\n10 = \");\n" +
"        for (j = 1; x[5] > 0; j++)\n" +
"        {\n" +
"            x[5]--;\n" +
"            txtOutput.append(\"*\");\n" +
"        }\n" +
"        \n" +
"        txtOutput.append(\"\\n------------------------------\\n\");\n" +
"    }");
    }
    private void NMayor()
    {
        double num1, num2;
        num1 = Double.parseDouble(JOptionPane.showInputDialog(null,"Cual es el primer numero?"));
        num2 = Double.parseDouble(JOptionPane.showInputDialog(null,"Cual es el segundo numero?"));
        if (num1 > num2)
        {
            txtOutput.append("El primer numero es mayor.");
        }
        if (num1 < num2)
        {
            txtOutput.append("El segundo numero es mayor.");
        }
        if (num1 == num2)
        {
            txtOutput.append("Son iguales.");
        }
        txtOutput.append("\n------------------------------\n");
    }
    private void sNMayor()
    {
        txtSource.setText("private void NMayor()\n" +
"    {\n" +
"        double num1, num2;\n" +
"        num1 = Double.parseDouble(JOptionPane.showInputDialog(null,\"Cual es el primer numero?\"));\n" +
"        num2 = Double.parseDouble(JOptionPane.showInputDialog(null,\"Cual es el segundo numero?\"));\n" +
"        if (num1 > num2)\n" +
"        {\n" +
"            txtOutput.append(\"El primer numero es mayor.\");\n" +
"        }\n" +
"        if (num1 < num2)\n" +
"        {\n" +
"            txtOutput.append(\"El segundo numero es mayor.\");\n" +
"        }\n" +
"        if (num1 == num2)\n" +
"        {\n" +
"            txtOutput.append(\"Son iguales.\");\n" +
"        }\n" +
"        txtOutput.append(\"\\n------------------------------\\n\");\n" +
"    }");
    }
    private void Dado2()
    {
        int x[] = new int [6];
        for(int i = 1; i <= 10000; i++)
        {
            int rand = (int)(Math.random()*6+0);
            x[rand]++;
        }
        txtOutput.append("Frecuencia del dado en 10000 intentos:\nCara 1: "+x[0]+"\nCara 2: "+x[1]+"\nCara 3: "+x[2]+"\nCara 4: "+x[3]+"\nCara 5: "+x[4]+"\nCara 6: "+x[5]);
        txtOutput.append("\n------------------------------\n");
    }
    private void sDado2()
    {
        txtSource.setText("private void Dado2()\n" +
"    {\n" +
"        int x[] = new int [6];\n" +
"        for(int i = 1; i <= 10000; i++)\n" +
"        {\n" +
"            int rand = (int)(Math.random()*6+0);\n" +
"            x[rand]++;\n" +
"        }\n" +
"        txtOutput.append(\"Frecuencia del dado en 10000 intentos:\\nCara 1: \"+x[0]+\"\\nCara 2: \"+x[1]+\"\\nCara 3: \"+x[2]+\"\\nCara 4: \"+x[3]+\"\\nCara 5: \"+x[4]+\"\\nCara 6: \"+x[5]);\n" +
"        txtOutput.append(\"\\n------------------------------\\n\");");
    }
    private void SumaArreglos2()
    {
        int x [] = new int[20];
        for (int i = 1; i < 20; i++)
        {
            x[i] = new java.util.Random().nextInt(1000)+1;
        }
        for (int i = 1; i < 20; i++)
        {
            txtOutput.append(""+x[i]+"\n");
        }
        int suma = 0;
        for (int i = 1; i < 20; i++)
        {
            suma += x[i];
        }
        txtOutput.append("La suma es: "+suma); 
        txtOutput.append("\n------------------------------\n");
    }
    private void rSumaArreglos2()
    {
        txtSource.setText("private void SumaArreglos2()\n" +
"    {\n" +
"        int x [] = new int[20];\n" +
"        for (int i = 1; i < 20; i++)\n" +
"        {\n" +
"            x[i] = new java.util.Random().nextInt(1000)+1;\n" +
"        }\n" +
"        for (int i = 1; i < 20; i++)\n" +
"        {\n" +
"            System.out.println(x[i]);\n" +
"        }\n" +
"        int suma = 0;\n" +
"        for (int i = 1; i < 20; i++)\n" +
"        {\n" +
"            suma += x[i];\n" +
"        }\n" +
"        txtOutput.append(\"La suma es: \"+suma); \n" +
"        txtOutput.append(\"\\n------------------------------\\n\");\n" +
"    }");
    }
}

 

